server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.1.103:3100/loki/api/v1/push

scrape_configs:
- job_name: dummylogs
  static_configs:
  - targets:
      - localhost
  - labels:
      job: dummylogs
      __path__: "/var/promtail/logs/log.log"
